### ISSUE TITLE
Consider adding a `set` method for the sake of symmetry?

### ISSUE THREAD

**Issue by moufmouf** [mnapoli/simplex#3]
Hey Matthieu,

I'm using Simplex quite a lot for testing my service providers, and I'm even (dangerously) using it in a project right now.

There is something weird however. Because Simplex is Pimple + ContainerInterop, it has a `get` and `has` method, but no `set` method.

When writing code, this leads to weird looking stuff like this: https://github.com/thecodingmachine/doctrine-annotations-universal-module/blob/1.0/tests/DoctrineAnnotationsServiceProviderTest.php#L26-L32

If I wrote a simple pull-request to add a `set` method that is simply an alias to `offsetSet`, would you accept it, or do you consider it to be out of scope of Simplex?

**Comment by mnapoli** [comment]
I guess why not. I don't like things being duplicated (it's better to not have a choice), but in that case since we _must_ have `get()` and all array operations are only for BC with Pimple we could have a `set()` method and encourage using it (unless in a "Pimple" context).
