### ISSUE TITLE
Previous factory always called?

### ISSUE THREAD

**Issue by pmall** [mnapoli/simplex#5]
Hello,

First of all I love service provider interop and simplex - lightview and straightforward package, I use it extensively for my project. Thanks for this.

I noticed when I run this code : 

```php
<?php

use Simplex\Container;
use Interop\Container\ServiceProvider;

$root_path = __DIR__ . '/..';

require $root_path . '/vendor/autoload.php';

$container = new Container;

$container->register(new class implements ServiceProvider {

    public function getServices()
    {
        return [
            'test' => function ($container) {

                var_dump('test1');

                return 'value1';

            },
        ];
    }

});

$container->register(new class implements ServiceProvider {

    public function getServices()
    {
        return [
            'test' => function ($container) {

                var_dump('test2');

                return 'value2';

            },
        ];
    }

});

var_dump($container->get('test'));
```

Would produce this output : 

```php
string(8) "factory1"
string(8) "factory2"
string(6) "value2"
```

I through the point of passing a callable as a second parameter was to run the first factory only when needed, which is obviously not the case. Is this the expected behavior and I'm missing something? Thanks.

**Comment by mnapoli** [comment]
Hi, yes this is a good point, I don't think it should behave like that. At the moment I'm focusing my "open source" time on other projects, this one was an experiment for service providers interop work, but if you send a pull request I can merge it!

**Comment by pmall** [comment]
Ok I tried my best to implements this.

I had to change a bit the behaviour of ->extend() method. I guess the only way to implements this without braking the original extend method is to write a completely separate one only for service providers. It's up on you. See #6 .

**Comment by pmall** [comment]
I also just made a pull request not breaking any original tests. So the behavior is not the same for regural extend and extending service provider definitions. See #7. Up to you to choose between the two.

**Comment by mnapoli** [comment]
Hi @pmall have you followed the latest changes in the spec done by @moufmouf? See #8 which was just merged, it might solve your problem in line with the WIP standard.

**Comment by pmall** [comment]
Hi @mnapoli thanks I didn't see the change in the spec. As there is no more callable passed to the methods I assume the new version of simplex implements it correctly and the problem is solved. Thanks.
