### ISSUE TITLE
Does not fully respect container-interop v0.4 

### ISSUE THREAD

**Issue by pmall** [mnapoli/simplex#9]
As stated in the new container interop specification:

> As a side-effect, even if service provider B is declared before service provider A, it can still extend services declared in service provider A.

Which does not work with simplex. This is very important because without this objects construction depends on the order the service providers are defined.

I had a look at the source code and I can't figure out how to implement this at the moment. Whats your thoughts about this ?

Here's a simple test with the current version:

```php
<?php

require 'vendor/autoload.php';

use Interop\Container\ServiceProviderInterface;

use Simplex\Container;

class A implements ServiceProviderInterface
{
    public function getFactories()
    {
        return [];
    }

    public function getExtensions()
    {
        return [
            'test' => function ($container, string $previous) {

                return $previous . 'def';

            },
        ];
    }
}

class B implements ServiceProviderInterface
{
    public function getFactories()
    {
        return [
            'test' => function () { return 'abc'; },
        ];
    }

    public function getExtensions()
    {
        return [];
    }
}

$container = new Container;

$container->register(new A);
$container->register(new B);

var_dump($container->get('test')); // outputs 'abc'. Should be 'abcdef'.

**Comment by mnapoli** [comment]
That's a very good point, I'm not 100% sure (it's been some time since I've been into the spec), ping @moufmouf for confirmation that this is indeed the expected behavior?

**Comment by moufmouf** [comment]
@pmall You are completely right.
I just added a failing unit test to showcase your issue (#10).

**Comment by moufmouf** [comment]
Looking at what causes the issue, solving this might be harder than expected!

Here is the code that currently registers a service provider:

https://github.com/mnapoli/simplex/blob/master/src/Simplex/Container.php#L337-L357

As you can see, I first register factories, then extensions for a given service provider.

So the code 

```php
$container->register(new A);
$container->register(new B);
```

will register:

- Factories from A
- then extensions from A
- then factories from B
- then extensions from B

But the correct order should be:

- Factories from A
- then factories from B
- then extensions from A
- then extensions from B

Problem: to do that, we should have a "signal" that the user finished registering service providers.

Something like:

```php
// register only stores service providers in Simplex
$container->register(new A);
$container->register(new B);
// registerDone is doing the actual work
$container->registerDone();
```

But this looks really weird and is error prone for the end user.
We could also call "registerDone" automatically on the first "get" performed, but even with that, we will have a ton of edge cases.

So my proposal would be to simply drop the register function, and replace it by an array of service providers passed in the constructor of Simplex.

Something like:

```php
$serviceProviders = [new A, new B];
$container = new Simplex([], $serviceProviders);
```

This makes more sense to me. This is obviously a breaking change but the only sane way we can solve this issue I currently see.

What do you think guys?

**Comment by pmall** [comment]
@moufmouf I totally agree with the array constructor parameter approach. In my opinion it is even clearer than allowing to register service providers in multiple places, I can't see any use case for that.

**Comment by moufmouf** [comment]
Solved by https://github.com/mnapoli/simplex/pull/11
